.gitignore, firebase.ts, pages/index.tsx
=> set up firebase

context/CanvasContext.tsx, context/UserContext.tsx, firebase/firebaseConfig.ts, pages/_app.tsx, pages/index.tsx
- Created context for user related states and functions
- Moved in the googleSignIn function to the context 
- Added signOut function and applied them in code (index.ts for now) 
- The "CanvasContext" is a context template for later use
#4
=> Created Context for User

components/Header.tsx, components/Layout.tsx, components/Sidebar.tsx, pages/_app.tsx, stylesheet/global.css
added layout, header and sidebar with simple styling
=> added layout, header and sidebar with simple styling

components/Header.tsx, components/shared/IconWithText.tsx, components/theme.ts, pages/_app.tsx, pages/index.tsx
- Created theme.ts and added theme styling for h1-body2, button and palette etc
- Applied theme in app and header
- Added the components in index as a "showcase" for now
#16
=> #16 mui theme

components/Layout.tsx, pages/admin/posterForm.tsx
- Form for creating posters
- Preview of image uploaded
- Responsive
=> added basic form and disabled sidebar when url includes admin

pages/admin/createPoster.tsx
Added functionality to upload a poster from the form. Right now there's only an alert as feedback. To test go to /admin/createPoster
**TO DO IN ANOTHER BRANCH**
- Fix a loader for when submitting the form.
- Use toasters instead of alerts.
- Move all types to types file instead.
=> Uploading to the database now works.

components/BackgroundForm.tsx, components/BgCheckBox.tsx, components/PosterCheckBox.tsx, lib/valSchemas.ts, pages/admin/createBackground.tsx
- Updated types, categories is now called posterCategories.
- Created type for backgroundCategories.
- Created val schema for bgr and also created a type from it called BackgroundData.
- Form complete with validation.
- Changed name of FormCheckBox to PosterCheckBox.
- Created new component called BgCheckBox - identica to PosterCheckBox but with correct typings for the background. Tried at first to use FormCheckBox, but since the typings in the props will be totally different it was easier to create a new component, instead of using the same one.
=> 36 5 1 create form with validation for background upload

components/BackgroundForm.tsx, components/BgCheckBox.tsx, components/PosterCheckBox.tsx, components/sidebar/BgSectionDetails.tsx, components/types.ts, context/SidebarContext.tsx, lib/valSchemas.ts, next.config.js, pages/admin/createBackground.tsx, pages/index.tsx
- Uploaded backgrounds are now fetched with the _getStaticProps_ function in _index.ts_
- Updated the prop type for the _Home_ component. It now gets the correct typings. However we should update the type for the Frames also.  (see imgs below)
- Updated the _backgroundCategory_-variables in the _sidebarcontext_ to work - they had to be updated since the bgs fetched from the db can have more than one category.
- Also updated the filtering functions in _FrameSectionDetails_, now we can apply more than one filter at a time. 
- Added our img domain to our next safelist so we can use their Image component.
=> 32 8 2 insert uploaded background in sidebar

components/canvas/Test.tsx, components/shared/CanvasFrame.tsx, components/sidebar/FrameSectionDetails.tsx, components/types.ts, context/CanvasContext.tsx, data/frameData.ts
- Restyled the frames, and created a dynamic component "CanvasFrame" for all 4 frame styles
- Added a new state frameSet as an object of frame.id, frame.title and size to replace the old "frame" state that is not using anymore
- Change frame color according to user's selection
- Currently there is only one frame that will be created. I have created a new issue for creating multiple frames. The empty unused "canvas" state in CanvasContext will be used for that 
- The frame components (not for canvas or preview) I created earlier are not removed as we may still need it in the future - will delete them before end of this project
- The poster is also positioned so it wont be shrinking when passepartout is applied
#34
=> #34 display frames

components/canvas/Test.tsx, components/shared/CanvasFrame.tsx, components/sidebar/FrameSectionDetails.tsx, components/sidebar/PosterSectionDetails.tsx, components/types.ts, context/CanvasContext.tsx
- Displays multiple frames and set different X position for each new frame created 
- Created a few new states and useEffect in the canvas to keep track on the user selections and save them in the states
- Shaped the "canvas" state and added whatever that is related to the frame except position (and background as well, but not user, createdAt etc). This state is for uploading the canvas object to db under canvas collection 
- Replaced the src of the frames from frameSet to canvas. The poster and withPassePartout is also retrieved from the canvas state now
**TODO: Not in this issue but todos are as commented in my code! 😃**
#48
=> #48 multiple frames

components/Sidebar.tsx, components/canvas/Test.tsx, components/helper.ts, components/shared/CanvasFrame.tsx, components/sidebar/AddFrameButton.tsx, components/sidebar/PosterSectionDetails.tsx, context/CanvasContext.tsx, context/SidebarContext.tsx
- Added function in helper to convert dimension object {width, height} to size string 
- Moved "size" state to canvas context 
- Added the adjusted (dragged) size to the "item" state
- Remove frameSets state and function as it is not in use 
- **NOTE: The adjusted size is not reflected in the canvas state for now as you said you want to adjust the "items" function so it uses id instead. This part will be in a new issue and only update when the new "items" function is ready**
#65
=> #65 update state when resizing frame

components/Layout.tsx, components/shared/RotateDevice.tsx, pages/canvas.tsx, stylesheet/rotate.module.css
- Fixed conditional rendering for if phone is portrait mode.
- Created component for portraitMode.
=> 72 22 1 mobile device suggest landscape mode

components/Layout.tsx, components/shared/RotateDevice.tsx
- This should fix the rotate screen not updating correctly.
- Worked on iPhone 8 running Safari.
- Worked on android running Chrome.
- Worked on pc desktop using Chrome.
=> 96 the rotate screen page doesnt show up once the user logged in from homepage

components/Sidebar.tsx, components/frames/framePreview/PlainBlackPreview.tsx, components/frames/framePreview/PlainMaplePreview.tsx, components/frames/framePreview/PlainWalnutPreview.tsx, components/frames/framePreview/PlainWhitePreview.tsx, components/sidebar/BgSection.tsx, components/sidebar/BgSectionDetails.tsx, components/sidebar/FrameSection.tsx, components/sidebar/PosterSection.tsx, components/sidebar/PosterSectionDetails.tsx
This fixes the error where it displayed the desktop sidebar on some mobile devices.
=> 62 22 2 show mobile sidebar instead of desktop sidebar

components/Layout.tsx
=> fixed so rotate phone only show up on phone

components/BackgroundForm.tsx, components/Header.tsx, components/PosterForm.tsx, components/helper.ts, components/imageUpload/ImageUploadModal.tsx, components/imageUpload/UploadButton.tsx, components/sidebar/BgSectionDetails.tsx, components/sidebar/PosterSectionDetails.tsx, context/SidebarContext.tsx, context/UploadContext.tsx, lib/valSchemas.ts
- added filter to show only the backgrounds and posters by system and uploaded by the current user
- added sort to the backgrounds and posters so they show the user uploaded ones first (and sort them by createdAt)
- new category "User upload" added and all posters / backgrounds uploaded by users will fall into that category
- hid the "User upload" category in both admin forms
- a text is shown when the selected category (in both background and poster section) has no images
- disabled upload button for non-logged in user
#81 and #83 and #98
=> #81 and #83 display uploaded images

components/Header.tsx, components/Layout.tsx, components/canvas/CanvasItem.tsx, components/canvas/SaveModal.tsx, components/types.ts, context/CanvasContext.tsx, context/SaveContext.tsx, pages/_app.tsx, pages/admin/createBackground.tsx, pages/admin/createPoster.tsx, pages/canvas.tsx
**This fixes the following**
- If user is logged in they can save the canvas to the database. 
- If the canvas already exists in the db it updates that one with the new changes.
- When the user first saves the canvas they have to give it a title.
- Title is projected in the header.
- Notifying the user if the upload failed / succeeded with our snackbars.
**for next issue**
- If no local storage exists and the user has a saved canvas, it imports the canvas from db.
- If both local storage and database canvas exist the user should be able to choose which one they wanna use.
=> 79 17 1 add function to the save button

components/BackgroundForm.tsx, components/PosterForm.tsx, components/home/HomeFeatures.tsx, components/home/HomeHero.tsx, components/shared/SectionTitle.tsx, pages/404.tsx, pages/canvas.tsx, pages/index.tsx
- Added text content in the landing page 
- Styled the elements based on the text length
- Adjusted the metadata in index.tsx by taking in a few keywords from the hero section
#76
=> #76 text content in landing page

components/shared/Loader.tsx, context/CanvasContext.tsx, pages/canvas.tsx
This has something to do with how we're dynamically importing the canvas.
The problem is that we're trying to update the canvas component before it has been rendered, since it is rendered dynamically (After what I've understood from my research, do not quote me on this 😄 ). See [this thread](https://github.com/vercel/next.js/issues/36636).
I believe this is also what is causing this error in the console: 
Since the error is only exisitng in deploy I will try do multiple commits until I get it to work.
=> Scale for uploaded bg is not updating in deploy

components/Layout.tsx, components/Protected.tsx, components/home/HomeHeader.tsx, components/shared/403.tsx, components/shared/RotateDevice.tsx, pages/404.tsx
- Now there is no longer a scroll shown in the rotate, 404 and 403. I set the height to 100vh - 200px and it is gone but I wonder why it is 200px but not 100px. I have done a quick testing and nothing else was affected by this setting, but please check too when you review this pr :)
#97 and #99
=> #97 and #99 Fixed scrollbars

components/Header.tsx, components/canvas/Canvas.tsx, components/canvas/SaveModal.tsx, components/home/HomeHero.tsx, components/imageUpload/ImageUploadForm.tsx, components/shared/PlainFrame.tsx, components/sidebar/BgSectionDetails.tsx
added a little style to the slider (not sure if you like it haha) and set maxWidth to the save textField
#127, #112
=> Css-css-css

components/helper.ts, pages/admin/createBackground.tsx, pages/admin/createPoster.tsx, public/robots.txt
- Little error fixed in the admin forms and the sorting function
- Added the robots.txt and disallow crawling of the /admin/*
#117
=> Some bug fixes, #117 robots.txt

context/SaveContext.tsx
**Fixes the following:**
- User property of canvas in database does not get deleted.
=> removed the deleteField thing which i for some reason have added

components/imageUpload/ImageUploadModal.tsx, context/UploadContext.tsx, pages/canvas.tsx
Increased the dimension limit as discussed now. Please test again if it is working
=> #140-increase-dimension-limit
